### ISSUE TITLE
Gran Canaria – Canary Islands

### ISSUE THREAD

**Issue by elitalon** [TheSwiftAlps/export#5]
This might be a long shot for people outside of Europe, but anyway just my two cents.

* Location: [Gran Canaria](https://en.wikipedia.org/wiki/Gran_Canaria) (you can [locate it](https://goo.gl/maps/ZFCCfY72f7r) on Google Maps).
* Recommended season: end of September, beginning of October.

It might be worth checking whether [The Surf Office](https://www.thesurfoffice.com/gran-canaria/) would have room for hosting this.

**Comment by bontoJR** [comment]
This option looks really, really, really interesting, I will keep an eye on it!
